### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by StevenCTimm** [fermitools/metacat#39]
This happened on Sunday night when Doug was trying to do some complicated parent/child MQL queries

Traceback (most recent call last):
  File "/exp/dune/app/home/dunepro/dpb/data-mgmt-ops/utilities/MetaChecker_date.py", line 165, in <module>
    childrenmd = mc_client.get_files(filemd["children"], with_metadata=True, with_provenance=True)
  File "/cvmfs/dune.opensciencegrid.org/products/dune/metacat/v3_42_2/NULL/lib/python3.9/site-packages/metacat/webapi/webapi.py", line 1166, in get_files
    return self.post_json(url, new_list) 
  File "/cvmfs/dune.opensciencegrid.org/products/dune/metacat/v3_42_2/NULL/lib/python3.9/site-packages/metacat/webapi/webapi.py", line 215, in post_json
    response = self.send_request("post", uri_suffix, data=data, headers=headers, stream=True)
  File "/cvmfs/dune.opensciencegrid.org/products/dune/metacat/v3_42_2/NULL/lib/python3.9/site-packages/metacat/webapi/webapi.py", line 168, in send_request
    raise WebAPIError(url, response)
metacat.webapi.webapi.WebAPIError: <html><body><h2>Application error</h2>
            <h3>out of shared memory
LINE 2:             temp_files_1714360417009 (
                    ^
HINT:  You might need to increase max_locks_per_transaction.
</h3>
            <pre>
Traceback (most recent call last):
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 644, in wsgi_call
    response = root_handler._handle_request(request, "", path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 437, in _handle_request
    return subhandler._handle_request(request, path + "/" + word, path_down, args)
  File "/home/dbidata3/multiserver/webpie/webpie/WPApp.py", line 435, in _handle_request
    return subhandler(request, relpath, **args)
  File "./metacat_server_dune/server/common_handler.py", line 93, in decorated
    try:    out = method(*params, **agrs)
  File "./metacat_server_dune/server/data_handler.py", line 1268, in files
    files = list(DBFile.get_files(db, lookup_lst))
  File "./metacat_server_dune/lib/metacat/common/dbbase.py", line 18, in decorated
    return method(first, *params, transaction=transaction, **args)
  File "./metacat_server_dune/lib/metacat/db/dbobjects2.py", line 685, in get_files
    transaction.execute(f"""create temp table if not exists
  File "/home/dbidata3/multiserver/wsdbtools/wsdbtools/transaction.py", line 28, in execute
    self.Cursor.execute(*params, **args)
psycopg2.errors.OutOfMemory: out of shared memory
LINE 2:             temp_files_1714360417009 (
                    ^
HINT:  You might need to increase max_locks_per_transaction.

</pre>
            </body>
            </html>

**Comment by alisonpeisker** [comment]
This is a resource problem on the database. I filed a service desk ticket with the database admins (RITM2089503) for help with this issue. Please let us know if you see this error again.

**Comment by marcmengel** [comment]
As there have been no further reports on this, I'm closing it out, and telling Olga to close out RITM2089503
